name: pomodoro_flutter
description: "This is an app for the study method of Pomodoro made in Flutter"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  intl: any
  flutter_local_notifications: ^19.2.1
  just_audio: ^0.10.3
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_lints: ^6.0.0
  freezed_lint: ^0.0.9
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
  shaders:
    - assets/shaders/sphere_fill.frag
